### ISSUE TITLE
Where I can take client secret and id?

### ISSUE THREAD

**Issue by mitrades** [gentor/olx-api-client#1]
Hi I send letter at link on European Documentation with Google forms, but they don't answer.

Maybe you know Where I can take client secret and id?

If I use my token access of already registered account of  user , I can't to add new ads by api, and I can't edit any information.

**Comment by juhacz** [comment]
Read http://partner-api.olx.pl/reference#getting-access, fill survey, and You recive client_id, client_secret.

**Comment by mitrades** [comment]
Hi I feel it but have not any reaction of it.

пн, 22 окт. 2018 г., 18:00 juhacz <notifications@github.com>:
